# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-19 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_title', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=256, verbose_name='Name')),
                ('genre_albums', models.ManyToManyField(blank=True, to='catalog.Album', verbose_name='Albums')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=256, verbose_name='Name')),
                ('singer_photo', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo')),
                ('singer_albums', models.ManyToManyField(blank=True, to='catalog.Album', verbose_name='Albums')),
            ],
            options={
                'verbose_name': 'Singer',
                'verbose_name_plural': 'Singers',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=256, verbose_name='Name')),
                ('track_song', models.FileField(upload_to='uploads')),
                ('track_album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Album', verbose_name='Album')),
            ],
            options={
                'verbose_name': 'Track',
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='album_genres',
            field=models.ManyToManyField(blank=True, to='catalog.Genre', verbose_name='Genres'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_singers',
            field=models.ManyToManyField(blank=True, to='catalog.Singer', verbose_name='Singers'),
        ),
    ]
