# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-19 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_tracks',
            field=models.ManyToManyField(blank=True, to='catalog.Track', verbose_name='Tracks'),
        ),
    ]
