# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-19 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_album_album_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_singers',
            field=models.ManyToManyField(blank=True, to='catalog.Singer', verbose_name='Singers'),
        ),
    ]
