# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-19 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_track_track_singers'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Genre', verbose_name='Genre'),
        ),
    ]
