# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-19 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_track_track_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo'),
        ),
    ]
