# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-19 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_album_album_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='track',
            name='track_photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Photo'),
        ),
    ]
